name: CI on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: [self-hosted, stuycs-k, linux]  # Use your runner's label

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run only if owner is stuycs-k
        if: github.repository_owner != 'stuycs-k'
        run: |
          echo "Running default tester..."
          chmod +x runner.sh
          ./runner.sh

      
